# Generated by Django 3.0.5 on 2020-05-17 09:11

from django.db import migrations, models
import users.storages


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200510_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', storage=users.storages.PublicStorage(), upload_to='profile_pics'),
        ),
    ]
