# Generated by Django 3.0.3 on 2020-02-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price_m2',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
