# Generated by Django 3.0.3 on 2020-02-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200223_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mpaa_rating',
            field=models.CharField(choices=[('-', 'None'), ('G', 'G rating'), ('PG-13', 'PG-13 rating'), ('NC-17', 'NC-17 rating')], default=0, max_length=5),
        ),
    ]
