# Generated by Django 3.0.2 on 2020-04-25 08:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=256, verbose_name='Brand name')),
                ('design', models.CharField(max_length=256, verbose_name='Design name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=3)),
                ('video', models.FileField(blank=True, default='', upload_to='videos/')),
                ('image', models.ImageField(default='', upload_to='pics/')),
            ],
            options={
                'verbose_name': 'T-shirt',
                'verbose_name_plural': 'T-shirts',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=400)),
                ('stars', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tshirts.Tshirt')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
