# Generated by Django 3.0.5 on 2020-05-10 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tshirts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tshirts.Story', to_field='body'),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='user',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='body',
            field=models.TextField(blank=True, help_text='Add a story connected with the T-shirt', max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='tshirt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tshirts.Tshirt'),
        ),
    ]
