# Generated by Django 3.0.5 on 2020-05-16 14:04

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tshirts', '0002_auto_20200515_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
