# Generated by Django 3.0.5 on 2020-05-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirts', '0003_auto_20200510_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='story',
        ),
        migrations.AddField(
            model_name='tshirt',
            name='story',
            field=models.ManyToManyField(null=True, related_name='_tshirt_story_+', to='tshirts.Story'),
        ),
    ]
