# Generated by Django 3.0.5 on 2020-05-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirts', '0004_auto_20200510_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='story',
            field=models.ManyToManyField(related_name='_tshirt_story_+', to='tshirts.Story'),
        ),
    ]
