# Generated by Django 3.0.5 on 2020-05-17 09:11

from django.db import migrations, models
import tshirts.storages


class Migration(migrations.Migration):

    dependencies = [
        ('tshirts', '0004_tshirt_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='image',
            field=models.ImageField(default='', storage=tshirts.storages.PublicStorage(), upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='video',
            field=models.FileField(blank=True, default='', storage=tshirts.storages.PublicStorage(), upload_to='videos/'),
        ),
    ]
