# Generated by Django 3.0.5 on 2020-05-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tshirts', '0005_auto_20200517_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='author',
        ),
    ]
